---
- name: install desktop packages
  pacman:
    name:
      - xorg-server-xwayland
      - xdg-user-dirs
    state: present

- name: install video packages
  pacman:
    name:
      - mesa
      - mesa-demos
      - lib32-virtualgl
      - vulkan-intel
      - lib32-vulkan-intel
      - intel-media-driver
      - libva-utils
      - vulkan-headers
      - vulan-icd-loader
      - vulkan-mesa-layers
      - vulkan-radeon
      - vulkan-tools
      - vulkan-validation-layers
    state: present

- name: install audio packages
  pacman:
    name:
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - wireplumber
      - pavucontrol
      - pamixer
      - alsa-utils
    state: present

- name: install applications packages
  pacman:
    name:
      - imv # img visualizer
      - kitty # terminal emulator
      - evince # pdf viewer
      - evolution # mail client
      - gnome-keyring # evolution gnome keyring
      - seahorse # keyring manager
      - firefox
      - flatpak # package manager
      - gimp # img editor
      - kolourpaint # img editor
      - shotwell # photo manager
      - libreoffice-still # libreoffice suite
      - mpv # video player
      - nemo # file manager
      - tumbler # thumbnailer
      - openvpn # vpn client
      - openconnect # globalprotect vpn client
      - playerctl # music player cli controller
      - rdesktop # remote desktop client
      - remmina # remote desktop client
      - freerdp # remmina dep for rdp
      - gnome-themes-extra # gtk themes
      #- x2goclient
      - youtube-dl
      - gopass # password manager
      - okular # pdf editor, no image overlay
      - xournalpp # pdf editor, no form
      - wezterm
      - cockpit
      - cockpit-machines
      - cockpit-podman
      - cockpit-packagekit
      - dolphin
      
    state: present

- name: add missing gpg keys for aur
  become: no
  shell: gpg --recv --keyserver keyserver.ubuntu.com '{{item}}'
  loop:
    - F4B432D5D67990E3 # wob

  changed_when: false

- name: install aur packages
  become: no
  aur:
    skip_installed: true
    name:
      - wf-recorder-git # screen recorder for wayland
      - grimshot-git # grim+slurp wrapper
      - waypipe # wayland ssh -X
      #- gnome-ssh-askpass2 # ssh askpass gui
      - google-chrome
      - adb-sync-git # android dir sync
      - downgrade # package downgrader
      - lf # cli file manager
      - otf-font-awesome
      #- ttf-impallari-cabin-font # xelatex cv
      - pastel # color viewer
      - swappy # screenshot editor
      - iwgtk # gui for iwd
      #- phockup # picture sorting tool
      - android-sdk-platform-tools
      - openrgb
      - waynergy-git
      - thorium-browser-bin
      - fastfetch-git
      - cava-git
      - logiops
      - looking-glass
      - cockpit-zfs-manager
      - sdbus-cpp-git #dependency of hyprland gtk portal git
      - hyprland-git
      - xdg-portal-hyprland-git
      - nwg-look
      - nwg-displays

- name: test swaylock-fancy
  stat:
    path: /bin/swaylock-fancy
  register: swaylock

- name: clone swaylock-fancy
  git:
    repo: https://github.com/eoli3n/swaylock-fancy
    dest: /tmp/swaylock-fancy
  when: not swaylock.stat.exists

- name: install swaylock-fancy
  shell: make install
  args:
    chdir: /tmp/swaylock-fancy
  when: not swaylock.stat.exists
